// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// - Remark: HTTP `POST /mail/send`.
    /// - Remark: Generated from `#/paths//mail/send/post(sendMail)`.
    func sendMail(_ input: Operations.sendMail.Input) async throws -> Operations.sendMail.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `POST /mail/send`.
    /// - Remark: Generated from `#/paths//mail/send/post(sendMail)`.
    public func sendMail(body: Components.RequestBodies.SendMailRequestBody) async throws -> Operations.sendMail.Output {
        try await sendMail(Operations.sendMail.Input(body: body))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    public enum Server1 {
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
                variables: []
            )
        }
    }
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
            variables: []
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
public enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/EmailField`.
        public typealias EmailField = Swift.String
        /// - Remark: Generated from `#/components/schemas/SendMailRequestSchema`.
        public struct SendMailRequestSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SendMailRequestSchema/email`.
            public var email: Components.Schemas.EmailField?
            /// Creates a new `SendMailRequestSchema`.
            ///
            /// - Parameters:
            ///   - email:
            public init(email: Components.Schemas.EmailField? = nil) {
                self.email = email
            }
            public enum CodingKeys: String, CodingKey {
                case email
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    public enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    public enum RequestBodies {
        /// - Remark: Generated from `#/components/requestBodies/SendMailRequestBody`.
        @frozen public enum SendMailRequestBody: Sendable, Hashable {
            /// - Remark: Generated from `#/components/requestBodies/SendMailRequestBody/content/application\/json`.
            case json(Components.Schemas.SendMailRequestSchema)
        }
    }
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {
        public struct SendMailAcceptedResponse: Sendable, Hashable {
            /// Creates a new `SendMailAcceptedResponse`.
            public init() {}
        }
        public struct BadInputResponse: Sendable, Hashable {
            /// Creates a new `BadInputResponse`.
            public init() {}
        }
    }
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    public enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
public enum Operations {
    /// - Remark: HTTP `POST /mail/send`.
    /// - Remark: Generated from `#/paths//mail/send/post(sendMail)`.
    public enum sendMail {
        public static let id: Swift.String = "sendMail"
        public struct Input: Sendable, Hashable {
            public var body: Components.RequestBodies.SendMailRequestBody
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - body:
            public init(body: Components.RequestBodies.SendMailRequestBody) {
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            /// Mail request accepted.
            ///
            /// - Remark: Generated from `#/paths//mail/send/post(sendMail)/responses/202`.
            ///
            /// HTTP response code: `202 accepted`.
            case accepted(Components.Responses.SendMailAcceptedResponse)
            /// Mail request accepted.
            ///
            /// - Remark: Generated from `#/paths//mail/send/post(sendMail)/responses/202`.
            ///
            /// HTTP response code: `202 accepted`.
            public static var accepted: Self {
                .accepted(.init())
            }
            /// The associated value of the enum case if `self` is `.accepted`.
            ///
            /// - Throws: An error if `self` is not `.accepted`.
            /// - SeeAlso: `.accepted`.
            public var accepted: Components.Responses.SendMailAcceptedResponse {
                get throws {
                    switch self {
                    case let .accepted(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "accepted",
                            response: self
                        )
                    }
                }
            }
            /// Bad input.
            ///
            /// - Remark: Generated from `#/paths//mail/send/post(sendMail)/responses/400`.
            ///
            /// HTTP response code: `400 badRequest`.
            case badRequest(Components.Responses.BadInputResponse)
            /// Bad input.
            ///
            /// - Remark: Generated from `#/paths//mail/send/post(sendMail)/responses/400`.
            ///
            /// HTTP response code: `400 badRequest`.
            public static var badRequest: Self {
                .badRequest(.init())
            }
            /// The associated value of the enum case if `self` is `.badRequest`.
            ///
            /// - Throws: An error if `self` is not `.badRequest`.
            /// - SeeAlso: `.badRequest`.
            public var badRequest: Components.Responses.BadInputResponse {
                get throws {
                    switch self {
                    case let .badRequest(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "badRequest",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
}
