// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// - Remark: HTTP `GET /todos`.
    /// - Remark: Generated from `#/paths//todos/get(listTodos)`.
    func listTodos(_ input: Operations.ListTodos.Input) async throws -> Operations.ListTodos.Output
    /// - Remark: HTTP `POST /todos`.
    /// - Remark: Generated from `#/paths//todos/post(createTodo)`.
    func createTodo(_ input: Operations.CreateTodo.Input) async throws -> Operations.CreateTodo.Output
    /// - Remark: HTTP `GET /todos/{todoId}`.
    /// - Remark: Generated from `#/paths//todos/{todoId}/get(getTodo)`.
    func getTodo(_ input: Operations.GetTodo.Input) async throws -> Operations.GetTodo.Output
    /// - Remark: HTTP `PUT /todos/{todoId}`.
    /// - Remark: Generated from `#/paths//todos/{todoId}/put(updateTodo)`.
    func updateTodo(_ input: Operations.UpdateTodo.Input) async throws -> Operations.UpdateTodo.Output
    /// - Remark: HTTP `DELETE /todos/{todoId}`.
    /// - Remark: Generated from `#/paths//todos/{todoId}/delete(deleteTodo)`.
    func deleteTodo(_ input: Operations.DeleteTodo.Input) async throws -> Operations.DeleteTodo.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `GET /todos`.
    /// - Remark: Generated from `#/paths//todos/get(listTodos)`.
    public func listTodos(headers: Operations.ListTodos.Input.Headers = .init()) async throws -> Operations.ListTodos.Output {
        try await listTodos(Operations.ListTodos.Input(headers: headers))
    }
    /// - Remark: HTTP `POST /todos`.
    /// - Remark: Generated from `#/paths//todos/post(createTodo)`.
    public func createTodo(
        headers: Operations.CreateTodo.Input.Headers = .init(),
        body: Components.RequestBodies.TodoRequestBody
    ) async throws -> Operations.CreateTodo.Output {
        try await createTodo(Operations.CreateTodo.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /todos/{todoId}`.
    /// - Remark: Generated from `#/paths//todos/{todoId}/get(getTodo)`.
    public func getTodo(
        path: Operations.GetTodo.Input.Path,
        headers: Operations.GetTodo.Input.Headers = .init()
    ) async throws -> Operations.GetTodo.Output {
        try await getTodo(Operations.GetTodo.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PUT /todos/{todoId}`.
    /// - Remark: Generated from `#/paths//todos/{todoId}/put(updateTodo)`.
    public func updateTodo(
        path: Operations.UpdateTodo.Input.Path,
        headers: Operations.UpdateTodo.Input.Headers = .init(),
        body: Components.RequestBodies.TodoRequestBody
    ) async throws -> Operations.UpdateTodo.Output {
        try await updateTodo(Operations.UpdateTodo.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `DELETE /todos/{todoId}`.
    /// - Remark: Generated from `#/paths//todos/{todoId}/delete(deleteTodo)`.
    public func deleteTodo(path: Operations.DeleteTodo.Input.Path) async throws -> Operations.DeleteTodo.Output {
        try await deleteTodo(Operations.DeleteTodo.Input(path: path))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    public enum Server1 {
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
                variables: []
            )
        }
    }
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
            variables: []
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
public enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/TodoSchema`.
        public struct TodoSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/TodoSchema/id`.
            public var id: Components.Schemas.TodoIdField
            /// - Remark: Generated from `#/components/schemas/TodoSchema/name`.
            public var name: Components.Schemas.TodoNameField
            /// - Remark: Generated from `#/components/schemas/TodoSchema/isCompleted`.
            public var isCompleted: Components.Schemas.TodoIsCompletedField
            /// Creates a new `TodoSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - name:
            ///   - isCompleted:
            public init(
                id: Components.Schemas.TodoIdField,
                name: Components.Schemas.TodoNameField,
                isCompleted: Components.Schemas.TodoIsCompletedField
            ) {
                self.id = id
                self.name = name
                self.isCompleted = isCompleted
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case name
                case isCompleted
            }
        }
        /// - Remark: Generated from `#/components/schemas/TodoIdField`.
        public typealias TodoIdField = Swift.String
        /// - Remark: Generated from `#/components/schemas/TodoNameField`.
        public typealias TodoNameField = Swift.String
        /// - Remark: Generated from `#/components/schemas/TodoIsCompletedField`.
        public typealias TodoIsCompletedField = Swift.Bool
        /// - Remark: Generated from `#/components/schemas/TodoCreateSchema`.
        public struct TodoCreateSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/TodoCreateSchema/name`.
            public var name: Components.Schemas.TodoNameField
            /// - Remark: Generated from `#/components/schemas/TodoCreateSchema/isCompleted`.
            public var isCompleted: Components.Schemas.TodoIsCompletedField
            /// Creates a new `TodoCreateSchema`.
            ///
            /// - Parameters:
            ///   - name:
            ///   - isCompleted:
            public init(
                name: Components.Schemas.TodoNameField,
                isCompleted: Components.Schemas.TodoIsCompletedField
            ) {
                self.name = name
                self.isCompleted = isCompleted
            }
            public enum CodingKeys: String, CodingKey {
                case name
                case isCompleted
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    public enum Parameters {
        /// Todo identifier
        ///
        /// - Remark: Generated from `#/components/parameters/TodoIdParameter`.
        public typealias TodoIdParameter = Components.Schemas.TodoIdField
    }
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    public enum RequestBodies {
        /// - Remark: Generated from `#/components/requestBodies/TodoRequestBody`.
        @frozen public enum TodoRequestBody: Sendable, Hashable {
            /// - Remark: Generated from `#/components/requestBodies/TodoRequestBody/content/application\/json`.
            case json(Components.Schemas.TodoCreateSchema)
        }
    }
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {
        public struct TodoListResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/TodoListResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/TodoListResponse/content/application\/json`.
                case json([Components.Schemas.TodoSchema])
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: [Components.Schemas.TodoSchema] {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.TodoListResponse.Body
            /// Creates a new `TodoListResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.TodoListResponse.Body) {
                self.body = body
            }
        }
        public struct TodoResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/TodoResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/TodoResponse/content/application\/json`.
                case json(Components.Schemas.TodoSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.TodoSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.TodoResponse.Body
            /// Creates a new `TodoResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.TodoResponse.Body) {
                self.body = body
            }
        }
    }
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    public enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
public enum Operations {
    /// - Remark: HTTP `GET /todos`.
    /// - Remark: Generated from `#/paths//todos/get(listTodos)`.
    public enum ListTodos {
        public static let id: Swift.String = "listTodos"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/todos/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.ListTodos.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.ListTodos.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.ListTodos.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.ListTodos.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            /// Todo list response
            ///
            /// - Remark: Generated from `#/paths//todos/get(listTodos)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Components.Responses.TodoListResponse)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Components.Responses.TodoListResponse {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `POST /todos`.
    /// - Remark: Generated from `#/paths//todos/post(createTodo)`.
    public enum CreateTodo {
        public static let id: Swift.String = "createTodo"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/todos/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.CreateTodo.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.CreateTodo.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.CreateTodo.Input.Headers
            public var body: Components.RequestBodies.TodoRequestBody
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.CreateTodo.Input.Headers = .init(),
                body: Components.RequestBodies.TodoRequestBody
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            /// Todo response
            ///
            /// - Remark: Generated from `#/paths//todos/post(createTodo)/responses/201`.
            ///
            /// HTTP response code: `201 created`.
            case created(Components.Responses.TodoResponse)
            /// The associated value of the enum case if `self` is `.created`.
            ///
            /// - Throws: An error if `self` is not `.created`.
            /// - SeeAlso: `.created`.
            public var created: Components.Responses.TodoResponse {
                get throws {
                    switch self {
                    case let .created(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "created",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `GET /todos/{todoId}`.
    /// - Remark: Generated from `#/paths//todos/{todoId}/get(getTodo)`.
    public enum GetTodo {
        public static let id: Swift.String = "getTodo"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/todos/{todoId}/GET/path`.
            public struct Path: Sendable, Hashable {
                /// Todo identifier
                ///
                /// - Remark: Generated from `#/paths/todos/{todoId}/GET/path/todoId`.
                public var todoId: Components.Parameters.TodoIdParameter
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - todoId: Todo identifier
                public init(todoId: Components.Parameters.TodoIdParameter) {
                    self.todoId = todoId
                }
            }
            public var path: Operations.GetTodo.Input.Path
            /// - Remark: Generated from `#/paths/todos/{todoId}/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetTodo.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetTodo.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.GetTodo.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            public init(
                path: Operations.GetTodo.Input.Path,
                headers: Operations.GetTodo.Input.Headers = .init()
            ) {
                self.path = path
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            /// Todo response
            ///
            /// - Remark: Generated from `#/paths//todos/{todoId}/get(getTodo)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Components.Responses.TodoResponse)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Components.Responses.TodoResponse {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `PUT /todos/{todoId}`.
    /// - Remark: Generated from `#/paths//todos/{todoId}/put(updateTodo)`.
    public enum UpdateTodo {
        public static let id: Swift.String = "updateTodo"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/todos/{todoId}/PUT/path`.
            public struct Path: Sendable, Hashable {
                /// Todo identifier
                ///
                /// - Remark: Generated from `#/paths/todos/{todoId}/PUT/path/todoId`.
                public var todoId: Components.Parameters.TodoIdParameter
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - todoId: Todo identifier
                public init(todoId: Components.Parameters.TodoIdParameter) {
                    self.todoId = todoId
                }
            }
            public var path: Operations.UpdateTodo.Input.Path
            /// - Remark: Generated from `#/paths/todos/{todoId}/PUT/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.UpdateTodo.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.UpdateTodo.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.UpdateTodo.Input.Headers
            public var body: Components.RequestBodies.TodoRequestBody
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            ///   - body:
            public init(
                path: Operations.UpdateTodo.Input.Path,
                headers: Operations.UpdateTodo.Input.Headers = .init(),
                body: Components.RequestBodies.TodoRequestBody
            ) {
                self.path = path
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            /// Todo response
            ///
            /// - Remark: Generated from `#/paths//todos/{todoId}/put(updateTodo)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Components.Responses.TodoResponse)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Components.Responses.TodoResponse {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// - Remark: HTTP `DELETE /todos/{todoId}`.
    /// - Remark: Generated from `#/paths//todos/{todoId}/delete(deleteTodo)`.
    public enum DeleteTodo {
        public static let id: Swift.String = "deleteTodo"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/todos/{todoId}/DELETE/path`.
            public struct Path: Sendable, Hashable {
                /// Todo identifier
                ///
                /// - Remark: Generated from `#/paths/todos/{todoId}/DELETE/path/todoId`.
                public var todoId: Components.Parameters.TodoIdParameter
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - todoId: Todo identifier
                public init(todoId: Components.Parameters.TodoIdParameter) {
                    self.todoId = todoId
                }
            }
            public var path: Operations.DeleteTodo.Input.Path
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            public init(path: Operations.DeleteTodo.Input.Path) {
                self.path = path
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct NoContent: Sendable, Hashable {
                /// Creates a new `NoContent`.
                public init() {}
            }
            /// Todo deleted
            ///
            /// - Remark: Generated from `#/paths//todos/{todoId}/delete(deleteTodo)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            case noContent(Operations.DeleteTodo.Output.NoContent)
            /// Todo deleted
            ///
            /// - Remark: Generated from `#/paths//todos/{todoId}/delete(deleteTodo)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            public static var noContent: Self {
                .noContent(.init())
            }
            /// The associated value of the enum case if `self` is `.noContent`.
            ///
            /// - Throws: An error if `self` is not `.noContent`.
            /// - SeeAlso: `.noContent`.
            public var noContent: Operations.DeleteTodo.Output.NoContent {
                get throws {
                    switch self {
                    case let .noContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "noContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
}
